spring:
  cloud:
    gateway:
      routes:
      - id: postsModule
        uri: http://localhost:8082/
        predicates:
        - Path=/post/**
      - id: usersModule
        uri: http://localhost:8083/
        predicates:
        - Path=/user/**
